pyChess/olaf/urls.py
from django.conf.urls import url

from . import views

app_name = 'olaf'
urlpatterns = [#function assignment
	url ( r'^login/$', views.login_user, name = 'login' ),
	url ( r'^register/$', views.register_user, name = 'register' ),
	url ( r'^reset_password/$', views.password_reset_request, name = 'reset_password' ),
	url ( r'^reset_password/([0-9A-Za-z\-]*)/?$', views.reset_password_action, name = 'reset_password_action' ),
	url ( r'^activate/([0-9A-Za-z\-]*)/?$', views.activate_account, name = 'activate_account' ),
	url ( r'^resend_email/$', views.resend_activation_email, name = 'resend_activation_email' ),
	url ( r'^logout/?$', views.logout_user, name = 'logout' ),
	url ( r'^scoreboard/?$', views.scoreboard, name = 'scoreboard' ),
	url ( r'^move/?$', views.move, name = 'move_parser' ),

	#url ( r'^profile/?$', , name = 'profile' ),
	#url ( r'^user/([a-zA-Z][a-zA-Z0-9_]*)/?$', , name = 'user_profile' ),
]

pyChess/pyChess/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from olaf import views

urlpatterns = [
	url ( r'^$',views.index , name = 'index' ),
	url ( r'^', include ( 'olaf.urls' ) )
]

pyChess/olaf/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

# Create your models here.

class UserData ( models.Model ):
	master = models.OneToOneField ( User, on_delete = models.CASCADE )

	wins = models.IntegerField ( default = 0 )
	ties = models.IntegerField ( default = 0 )
	loses = models.IntegerField ( default = 0 )

	is_active = models.BooleanField ( default = False )

	@property
	def recent_game ( self ):
		if ( hasattr ( self, 'game_history' ) ):
			return self.game_history.filter ( is_recent = True ).first ()
		return None

	class Meta:
		ordering = [ '-wins', 'loses', '-ties' ]

class GameBoard ( models.Model ):
	INITIAL_STATE = '4qJUX2X8bojZVNRp1nOF053R9sMHhefbMuOkdSf4Uo'
	state = models.CharField ( max_length = 64, default = INITIAL_STATE )
	creation_time = models.DateTimeField ( auto_now_add = True )
	result = models.IntegerField ( default = 0 )

	is_recent = models.BooleanField ( default = False )
	user = models.ForeignKey ( UserData, on_delete = models.CASCADE, related_name = 'game_history' )

class CustomEmailField ( models.Model ):
	email = models.EmailField ( max_length = 64 )
	is_primary = models.BooleanField ( default = False )
	user = models.ForeignKey ( UserData, on_delete = models.CASCADE, related_name = 'email_list' )

class ExpirableTokenField ( models.Model ):
	token = models.CharField ( max_length = 256 )
	expiration_time = models.DateTimeField ()
	user = models.OneToOneField ( UserData, on_delete = models.CASCADE, related_name = 'token' )

pyChess/olaf/forms.py
from django import forms

from django.contrib.auth import authenticate

from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from olaf.validators import *

class LoginForm ( forms.Form ):
	username = forms.CharField (
		label = "Username",
		max_length = 64,
		validators = [
			validate_username_login_availability,
			validate_username_login_activatability
		],
		widget = forms.TextInput ( attrs = { 'placeholder' : 'Username' } )
	)
	password = forms.CharField (
		label = "Password",
		widget = forms.PasswordInput ( attrs = { 'placeholder' : 'Password' } )
	)

	def clean ( self ):
		super ( LoginForm, self ).clean ()

		username = self.cleaned_data.get ( 'username' )
		password = self.cleaned_data.get ( 'password' )
		user = authenticate ( username = username, password = password )

		if ( (username is not None) and (password is not None) and (user is None) ):
			self.add_error ( 'password', ValidationError ( _( "Wrong Password" ), code = "incorrect_password" ) )

class RegisterForm ( forms.Form ):
	username = forms.CharField (
		label = "Username",
		max_length = 64,
		validators = [
			RegexValidator (
				regex = "^[a-zA-Z][a-zA-Z0-9_]*$",
				message = "Username should start with an alphabetic character and can only contain characters, numbers and underscore",
				code = "invalid_username"
			),
			validate_username_register_availability,
		],
		widget = forms.TextInput ( attrs = { 'placeholder' : 'Username' } )
	)

	email = forms.EmailField (
		label = "Email",
		validators = [ validate_email_register_availability ],
		widget = forms.TextInput ( attrs = { 'placeholder' : 'Email' } )
	)

	password = forms.CharField (
		label = "Password",
		widget = forms.PasswordInput ( attrs = { 'placeholder' : 'Passwrod' } )

	)
	confirm_password = forms.CharField (
		label = "Confirm Password",
		widget = forms.PasswordInput ( attrs = { 'placeholder' : 'Confirm password' } )
	)

	def clean ( self ):
		super ( RegisterForm, self ).clean ()

		password = self.cleaned_data.get ( 'password' )
		confirm_password = self.cleaned_data.get ( 'confirm_password' )

		if ( (password is not None) and (confirm_password is not None) and password != confirm_password ):
			self.add_error ( 'confirm_password', ValidationError ( _( "Passwords Dont Match" ), "no_password_match" ) )

class ResendActivationUsernameOrEmailForm ( forms.Form ):
	search_key = forms.CharField (
		label = "Username or Email",
		max_length = 64, 
		validators = [ validate_user_search_key ],
		widget = forms.TextInput ( attrs = { 'placeholder' : 'Username or Email' } )
	)

class ForgotPasswordUsernameOrEmailForm ( forms.Form ):
	search_key = forms.CharField (
		label = "Username or Email",
		max_length = 64, 
		validators = [
			validate_user_search_key,
			validate_user_search_key_activatability
		],
		widget = forms.TextInput ( attrs = { 'placeholder' : 'Username or Email' } )
	)

class PasswordChangeForm ( forms.Form ):
	password = forms.CharField (
		label = "Password",
		widget = forms.PasswordInput ( attrs = { 'placeholder' : 'Password' } )
	)
	confirm_password = forms.CharField (
		label = "Confirm Password",
		widget = forms.PasswordInput ( attrs = { 'placeholder' : 'Confirm password' } )
	)

	def clean ( self ):
		super ( PasswordChangeForm, self ).clean ()

		password = self.cleaned_data.get ( 'password' )
		confirm_password = self.cleaned_data.get ( 'confirm_password' )

		if ( (password is not None) and (confirm_password is not None) and password != confirm_password ):
			self.add_error ( 'confirm_password', ValidationError ( _( "Passwords Dont Match" ), "no_password_match" ) )

class MoveForm ( forms.Form ):
	move = forms.CharField (
		label = "Move",
		max_length = 64,
		validators = [
			RegexValidator (
				regex = "^[a-hA-H][0-9] [a-hA-H][0-9]$",
				message = "Invalid Move",
				code = "invalid_move"
			)
		]
	)

pyChess/olaf/chess/controller.py
from olaf.chess.AI import decide
from olaf.chess.models import GameBoard as ChessBoard
from olaf.chess.models import InvalidMoveError, Pos

from olaf.models import GameBoard
from olaf.forms import MoveForm as FORM

def chess_move_parse ( s ):
	s = s.lower ()
	return Pos ( int ( s [ 1 ] ) - 1 ,ord ( s [ 0 ] ) - ord ( 'a' ) )

def proccess_move ( request ):
	if ( request.method != "POST" ):
		return None

	if ( request.POST.get ( 'move' ) is None ):
		return None

	form = FORM  ( request.POST )
	if ( not form.is_valid () ):
		request.session [ 'message' ] = "Invalid Move"
		return None

	if ( request.session.get ( 'game_id' ) is None ):
		request.session [ 'message' ] = "No Active Game"
		return None

	if ( GameBoard.objects.filter ( id = request.session [ 'game_id' ] ).first () is None ):
		del request.session [ 'game_id' ]
		request.session [ 'message' ] = "No Active Game"
		return None

	gameboard = GameBoard.objects.filter ( id = request.session [ 'game_id' ] ).first ()

	if ( gameboard.result != 0 ):
		del request.session [ 'game_id' ]		
		request.session [ 'message' ] = "The game is over already"
		return None
		
	g = ChessBoard ( gameboard.state )
	s, t = request.POST [ 'move' ].split ()

	try:
		g.move ( chess_move_parse ( s ), chess_move_parse ( t ), 1 )
	except InvalidMoveError:
		request.session [ 'message' ] = "Invalid Move"
		return None

	gameboard.state = str  ( g )
	gameboard.save ()

	if ( g.is_mate ( -1 ) ):
		print ( g._is_check ( -1 ) )
		gameboard.result = 1
		gameboard.save ()

		us = gameboard.user
		us.wins = us.wins + 1
		us.save ()
		
		request.session [ 'message' ] = "You've Won"
		return None

	if ( g.is_pot ( -1 ) ):
		gameboard.result = 3
		gameboard.save ()

		us = gameboard.user
		us.ties = us.ties + 1
		us.save ()
		
		request.session [ 'message' ] = "The game is Tied"
		return None

	print ( "before decide" )
	gameboard.state = decide ( g )[ 1 ]
	gameboard.save ()
	print ( "after decide" )

	g = ChessBoard ( gameboard.state )

	if ( g.is_mate ( 1 ) ):
		gameboard.result = 2
		gameboard.save ()

		us = gameboard.user
		us.loses = us.loses + 1
		us.save ()
		
		request.session [ 'message' ] = "You've Lost"
		return None

	if ( g.is_pot ( 1 ) ):
		gameboard.result = 3
		gameboard.save ()

		us = gameboard.user
		us.ties = us.ties + 1
		us.save ()
		
		request.session [ 'message' ] = "The game is Tied"
		return None

	return None

pyChess/olaf/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse

from django.utils import timezone

from olaf.models import *
from olaf.forms import *
from olaf.utility import usertools

from olaf.chess.controller import proccess_move

def index ( request ):
	args = {}

	message = request.session.pop ( 'message', default = None )
	if ( message is not None ):
		args [ 'message' ] = message

	if ( request.user.is_authenticated ):
		if ( request.method == 'POST' ):
			if ( request.POST.get ( 'game_id' ) is not None ):
				game_id = request.POST.get ( 'game_id' )
				if ( game_id == '-1' ):
					game_id = usertools.new_game ( request )

				request.session [ 'game_id' ] = game_id
			else:
				request.session.pop ( 'game_id', default = None )

		f = lambda a : str ( a.date () ) + " - " + str ( a.hour ) + ":" + str ( a.minute ) + ":" + str ( a.second )
		args [ 'game_list' ] = list ([str ( game.id ), f ( game.creation_time )] for game in request.user.userdata.game_history.filter ( result = 0 ).order_by ( '-creation_time' ) )

		if ( request.session.get ( 'game_id' ) is not None ):
			args [ 'game_board' ] = usertools.get_translated_game_board ( request )
		else:
			args [ 'game_board' ] = None

		return render ( request, 'olaf/index_logged_in.html', args )
	else:
		args [ 'login_form' ] = LoginForm ()
		args [ 'register_form' ] = RegisterForm ()
		args [ 'score' ] = list ( [user.master.username, user.wins, user.loses, user.ties] for user in UserData.objects.filter ( is_active = True ) )

		return render ( request, 'olaf/index_not_logged_in.html', args )

form_operation_dict = {
	'login' : (
		usertools.login_user,
		LoginForm,
		'olaf/login.html',
		{},
		'index',
		{ 'message' : "You're logged in. :)"}
	),
	'register' : (
		usertools.register_user,
		RegisterForm,
		'olaf/register.html',
		{},
		'index',
		{ 'message' : "An activation email has been sent to you" }
	),
	'password_reset_request' : (
		usertools.init_pass_reset_token,
		ForgotPasswordUsernameOrEmailForm,
		'olaf/password_reset_request.html',
		{},
		'index',
		{ 'message' : "An email containing the password reset link will be sent to your email"}
	),
	'reset_password' : (
		usertools.reset_password_action,
		PasswordChangeForm,
		'olaf/reset_password.html',
		{},
		'olaf:login',
		{ 'message' : "Password successfully changed, you can login now" }
	),
	'resend_activation_email' : (
		usertools.resend_activation_email,
		ResendActivationUsernameOrEmailForm,
		'olaf/resend_activation_email.html',
		{},
		'index',
		{ 'message' : "Activation email successfully sent to your email" }
	),
}
def form_operation ( request, oper, *args ):
	func, FORM, fail_template, fail_args, success_url, success_args = form_operation_dict [ oper ]

	if ( request.method == 'POST' ):
		form = FORM ( request.POST )

		if ( form.is_valid () ):
			func ( request, form, *args )

			for key in success_args:
				request.session [ key ] = success_args [ key ]
			return HttpResponseRedirect ( reverse ( success_url ) )
	else:
		form = FORM ()

	message = request.session.pop ( 'message', default = None )
	if ( message is not None ):
		fail_args [ 'message' ] = message

	fail_args [ 'form' ] = form
	return render ( request, fail_template, fail_args )

#view functions

def login_user ( request ):
	if ( request.user.is_authenticated ):
		return HttpResponseRedirect ( reverse ( 'index' ) )

	return form_operation ( request, 'login' )

def register_user ( request ):
	if ( request.user.is_authenticated ):
		return HttpResponseRedirect ( reverse ( 'index' ) )

	return form_operation ( request, 'register' )

def password_reset_request ( request ):
	if ( request.user.is_authenticated ):
		return HttpResponseRedirect ( reverse ( 'index' ) )

	return form_operation ( request, 'password_reset_request' )

def reset_password_action ( request, token ):
	if ( request.user.is_authenticated ):
		return HttpResponseRedirect ( reverse ( 'index' ) )

	tk = ExpirableTokenField.objects.filter ( token = token ).first ()
	if ( tk is None ):
		request.session [ 'message' ] = "Broken link"
		return HttpResponseRedirect ( reverse ( 'index' ) )
	else:
		if ( timezone.now () <= tk.expiration_time ):
			return form_operation ( request, 'reset_password', token )
		else:
			request.session [ 'message' ] = "Link expired, try getting a new one"
			return HttpResponseRedirect ( reverse ( 'olaf:reset_password' ) )

def activate_account ( request, token ):
	if ( request.user.is_authenticated ):
		return HttpResponseRedirect ( reverse ( 'index' ) )

	tk = ExpirableTokenField.objects.filter ( token = token ).first ()
	if ( tk is None ):
		request.session [ 'message' ] = "Broken link"
		return HttpResponseRedirect ( reverse ( 'index' ) )
	else:
		if ( timezone.now () <= tk.expiration_time ):
			if ( tk.user.is_active ):
				request.session [ 'message' ] = "Account already active"
				return HttpResponseRedirect ( reverse ( 'index' ) )
			else:
				userdata = tk.user
				userdata.is_active = True
				userdata.save ()

				request.session [ 'message' ] = "Your account has been activated successfully"
				return HttpResponseRedirect ( reverse ( 'olaf:login' ) )
		else:
			request.session [ 'message' ] = "Link expired, try getting a new one"
			return HttpResponseRedirect ( reverse ( 'olaf:resend_activation_email' ) )

def resend_activation_email ( request ):
	if ( request.user.is_authenticated ):
		return HttpResponseRedirect ( reverse ( 'index' ) )

	return form_operation ( request, 'resend_activation_email' )

def logout_user ( request ):
	usertools.logout_user ( request )

	request.session [ 'message' ] = "Goodbye :)"
	return HttpResponseRedirect ( reverse ( 'index' ) )

def scoreboard ( request ):
	if ( request.method == 'POST' ):
		username = request.POST.get ( 'username' )
		user = User.objects.filter ( username = username ).first ()

		if ( user is None ):
			request.session [ 'message' ] = "User not found"
			return HttpResponseRedirect ( reverse ( 'olaf:scoreboard' ) )
		else:
			return HttpResponseRedirect ( reverse ( 'olaf:user_profile', args = (username, ) ) )
	else:
		args = {}

		message = request.session.pop ( 'message', default = None )
		if ( message is not None ):
			args [ 'message' ] = message

		lst = [ (user.master.username, user.wins, user.loses, user.ties) for user in UserData.objects.filter ( is_active = True ) ]
		args [ 'lst' ] = lst

		if ( request.user.is_authenticated ):
			args [ 'logged_in' ] = True

		return render ( request, 'olaf/scoreboard.html', args )

def move ( request ):
	proccess_move ( request )

	return HttpResponseRedirect ( reverse ( 'index' ) )

pyChess/pyChess/templates/olaf/index_logged_in.html
{% load my_pack %}
{% load static %}
<html>
    <head>
        <style type="text/css">
            body {
                margin: 0 0 0 0;
            }

           .header {
                float: ;
                width: 100%;
                margin: 0px;
                height: 7%;
                background-color: rgb(29,30,66);
            }
            .header_item{
                float: left;
                padding: 4px;
                color: rgb(255, 102, 0);
                padding-top: 9px;
                margin-left: 7px;
                margin-right: 7px;
                font-weight: bold;
            }
            .message {
                background-color: rgb(102, 204, 255);
                width:100%;
                height:auto;
                padding-bottom: 10px;
                color: rgb(255, 0, 0);
                font-weight: bold;
                position: absolute;
                border-bottom-right-radius: 15px;
                border-bottom-left-radius: 15px;
                opacity: 0.75;
                text-align: center;
                font-size: 19;
            }
            .container {
                width: 100%;
                margin: 0px;
                height: 93%;
                background-color: rgb(90,22,22);
            } 

            .gameboard_wrapper {
                float: right;
                background-color: rgb(214,183,34);
                width: 480px;
                height: 480px;
                margin-right: 18%;
                margin-top:3%;
                padding: 20px;
                text-align: center;
                border-radius: 15px;
                border-color: rgb(103,152,152);
                border-width: 2px;
                border-style: solid;
            }

            .game_history_wrapper {
                float:left;
                width: 21%;
                height: 75%;
                overflow-y: auto;
                background-color: #4CAF50;
                margin-left: 5%;
                margin-top: 6%;
                border-radius: 15px;
                border-color: rgb(103,152,152);
                border-width: 2px;
                border-style: solid;
                padding: 15px;
            }
            .game_history_object {
                background-color: rgb(255, 133, 51);
                width: 100%;
                vertical-align: middle;
                margin-bottom: 10px;

                border-width: 1px;
                border-color: rgb(255, 133, 51);
                border-radius: 10px;

                font-weight: bold;
                font-size: 19;
                padding-top: 7px;
                padding-bottom: 7px;
                text-align: center;
            }

            .black {
                float: left;
                width: 60px;
                height: 60px;
                background-color: #999;
                    font-size:50px;
                text-align:center;
                display: table-cell;
                vertical-align:middle;
            }
            .white {
                float: left;
                width: 60px;
                height: 60px;
                background-color: #fff;
                    font-size:50px;
                text-align:center;
                display: table-cell;
                vertical-align:middle;
            }
        </style>
    </head>

    <body class = "body">
        <div class = "header">
            <div class = "header_item">
                <a href="{% url 'index' %}" style = "text-decoration: none; color: rgb(255, 102, 0);">Home</a>
            </div>
            <div class = "header_item">
                <a href="{% url 'olaf:scoreboard' %}" style = "text-decoration: none; color: rgb(255, 102, 0);">Scoreboard</a>
            </div>
            <div class = "header_item" style = "float:right;">
                <a href="{% url 'olaf:logout' %}" style = "text-decoration: none; color: rgb(255, 102, 0);">Logout</a>
            </div>
        </div>

        <div class = "container">
            {% if message %}
                <div class = "message">{{message}}</div>
            {% endif %}
            <div class = "gameboard_wrapper">
                {% for i in "01234567" %}
                    {% for j in "01234567" %}
                        {% if i|add:j|iseven %}
                            <div class = "white">
                                {% if game_board %}
                                    <!-{% static game_board|index:i|index:j %}-!>
                                    {{ game_board|index:i|index:j }}
                                {% endif %}
                            </div>
                        {% else %}
                            <div class = "black">
                                {% if game_board %}
                                    <!-{% static game_board|index:i|index:j %}-!>
                                    {{ game_board|index:i|index:j }}
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                <form action = "{% url 'olaf:move_parser' %}" method = "POST">
                    {% csrf_token %}
                    <input type = "text" name = "move" >
                    <input type = "submit" value = "move" >
                </form>
            </div>
            <div class = "game_history_wrapper">
                <form action = "{% url 'index' %}" method = "POST">
                    {% csrf_token %}
                    <button name= "game_id" type="submit" value="-1" class = "game_history_object" style="background-color: rgb(255, 102, 0)">New Game</button>
                    {% for game in game_list %}
                        <button name= "game_id" type="submit" value="{{game.0}}" class = "game_history_object">{{ game.1 }}</button>
                    {% endfor %}
                </form>
            </div>
        </div>
    </body>
</html>

pyChess/pyChess/templates/olaf/index_not_logged_in.html
<html>
    <head>
        <style type="text/css">
            body {
                margin: 0 0 0 0;
            }

           .header {
                float: ;
                width: 100%;
                margin: 0px;
                height: 7%;
                background-color: rgb(29,30,66);
            }
            .header_item {
                float: left;
                padding: 4px;
                color: rgb(255, 102, 0);
                padding-top: 9px;
                margin-left: 7px;
                margin-right: 7px;
                font-weight: bold;
            }
            .message {
                background-color: rgb(102, 204, 255);
                width:100%;
                height:auto;
                padding-bottom: 10px;
                color: rgb(255, 0, 0);
                font-weight: bold;
                position: absolute;
                border-bottom-right-radius: 15px;
                border-bottom-left-radius: 15px;
                opacity: 0.75;
                text-align: center;
                font-size: 19;
            }
            .container {
                width: 100%;
                margin: 0px;
                height: 93%;
                background-color: rgb(90,22,22);
            } 

            .sign_in_wrapper {
                float: right;
                background-color: rgb(214,183,34);
                width: 22%;
                height: auto;
                margin-right: 4%;
                margin-top:3%;
                text-align: center;
                border-bottom-right-radius: 15px;
                border-bottom-left-radius: 15px;
                border-color: rgb(103,152,152);
                border-width: 2px;
                border-style: solid;
            }
            input[type="text"] {
                width: 94%;
                background-color: #4CAF50;
                color: white;
                padding: 14px 20px;
                margin: 8px 3% 3%;
                border: none;
                border-radius: 4px;
                text-align: center;
            }
            input[type="password"] {
                width: 94%;
                background-color: #4CAF50;
                color: white;
                padding: 14px 20px;
                margin: 8px 3% 3%;
                border: none;
                border-radius: 4px;
                text-align: center;
            }
            .custom_submit {
                width: 94%;
                background-color: rgb(128, 0, 85);
                color: white;
                padding: 14px 20px;
                margin: 8px 3% 3%;
                border: none;
                border-radius: 4px;
                text-align: center;
            }
            .error_list {
                width: 94%;
                padding: 14px 20px;
                margin: 8px 3% 3%;
                border: none;
                text-align: left;
                color: red;
            }

            .input_element {
                margin: auto;
            }
            .scoreboard_wrapper {
                float: left;
                overflow-y: auto;
                width: 65%;
                margin-top:4%;
                margin: 3%;
                height: 85%;
                background-color: rgb(177,114,42);
                border-radius: 15px;
                border-color: rgb(103,152,152);
                border-width: 2px;
                border-style: solid;
            }
            .scoreboard_item {
                width: 94%;
                margin-right: 3%;
                margin-left: 3%;
                margin-top: 10px;
                border-width: 1px;
                background-color: #00960C;
                border-color: rgb(255, 51, 0);
                border-radius: 10px;
            }

            .sign_in_button {
                float:left;
                background-color: rgb(73,104,104);
                padding-top: 10px;
                padding-bottom: 10px;
                width: 50%;
                border: none;
                text-align: center;
            }

            .black {
                float: left;
                width: 128px;
                height: 128px;
                background-color: #999;
                    font-size:50px;
                text-align:center;
                display: table-cell;
                vertical-align:middle;
            }
            .white {
                float: left;
                width: 128px;
                height: 128px;
                background-color: #fff;
                    font-size:50px;
                text-align:center;
                display: table-cell;
                vertical-align:middle;
            }

            .is_active {
                border-bottom-width: 2px;
                background-color: rgb(103,152,152);
                border-bottom-style: solid;
                border-bottom-color: rgb(90,22,22);
            }
        </style>
        <script type = "text/javascript">
            function LoginClick() {
                var login_header = document.getElementById('login_header');
                var register_header = document.getElementById('register_header');
                var login = document.getElementById('login');
                var register = document.getElementById('register');

                login.style.display = 'block';
                login_header.className = register_header.className.replace ( /(?:^|\s)is_active(?!\S)/g , '' )
                login_header.className += " is_active";

                register.style.display = 'none';
                register_header.className = register_header.className.replace ( /(?:^|\s)is_active(?!\S)/g , '' )
            }
            function RegisterClick() {
                var login_header = document.getElementById('login_header');
                var register_header = document.getElementById('register_header');
                var login = document.getElementById('login');
                var register = document.getElementById('register');

                register.style.display = 'block';
                register_header.className = login_header.className.replace ( /(?:^|\s)is_active(?!\S)/g , '' )
                register_header.className += " is_active";

                login.style.display = 'none';
                login_header.className = login_header.className.replace ( /(?:^|\s)is_active(?!\S)/g , '' )
            }
        </script>
    </head>

    <body class = "body">
        <div class = "header">
            <div class = "header_item">
                <a href="{% url 'index' %}" style = "text-decoration: none; color: rgb(255, 102, 0);">Home</a>
            </div>
            <div class = "header_item">
                <a href="{% url 'olaf:scoreboard' %}" style = "text-decoration: none; color: rgb(255, 102, 0);">Scoreboard</a>
            </div>
        </div>
        <div class = "container">
            {% if message %}
                <div class = "message">{{message}}</div>
            {% endif %}
            <div class = "sign_in_wrapper">
                <div>
                    <input type = "submit" id = "login_header" value = "Login" class = "sign_in_button is_active" onclick = "LoginClick()">
                </div>
                <div>
                    <input type = "submit" id = "register_header" value = "Register" class = "sign_in_button" onclick = "RegisterClick()">
                </div>
                <div id = "register" style = "display: none;">
                    <form action = "{% url 'olaf:register' %}" method = "POST">
                        {% csrf_token %}
                        {% for field in register_form %}
                            {{ field }}
                            {% if field.errors %}
                                <div class = "error_list">{{ field.errors }}</div>
                            {% endif %}
                        {% endfor %}
                        <input type = "submit" value = "Register" class = "custom_submit">
                    </form>
                </div>
                <div id = "login">
                    <form action = "{% url 'olaf:login' %}" method = "POST">
                        {% csrf_token %}
                        {% for field in login_form %}
                            {{ field }}
                            {% if field.errors %}
                                <div class = "error_list">{{ field.errors }}</div>
                            {% endif %}
                        {% endfor %}
                        <input type = "submit" value = "Login" class = "custom_submit">
                    </form>
                </div>
            </div>
            <div class = "scoreboard_wrapper">
                {% for item in score %}
                    <div class = "scoreboard_item">{{ item.0 }} : {{ item.1 }} Wins, {{ item.2 }} Loses and {{ item.3 }} Ties</div>
                {% endfor %}
            </div>
        </div>
    </body>
</html>